// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  on_tv: dynamic(() => import("./OnTv")),
  professional: dynamic(() => import("./Professional")),
  projects: dynamic(() => import("./Projects")),
};
